# Generated by Django 4.2.7 on 2023-11-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mediate_top', models.FloatField()),
                ('Mediate_chest', models.FloatField()),
                ('Mediate_shoulder', models.FloatField()),
                ('Mediate_arm', models.FloatField()),
                ('Mediate_neck', models.FloatField()),
                ('Mediate_ntk', models.FloatField()),
                ('Mediate_waist', models.FloatField()),
                ('Mediate_ass', models.FloatField()),
                ('Mediate_bottom', models.FloatField()),
                ('Mediate_thighs', models.FloatField()),
            ],
        ),
    ]
